import AppKit
import Foundation
import UniformTypeIdentifiers

@MainActor
final class PasteboardMonitor {
    var onSnapshot: ((ClipboardSnapshot, String?) -> Void)?
    var ignoredBundleIdentifiers: Set<String> = []

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var suppressedUntil = Date.distantPast
    private(set) var isPaused = false
    private var pausedUntil: Date?

    private(set) var isIgnoringNextCopy = false

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func suppressCapture(for duration: TimeInterval = 0.8) {
        suppressedUntil = Date().addingTimeInterval(duration)
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func ignoreNextCopy() {
        isIgnoringNextCopy = true
    }

    func pauseHistory(for duration: ClipboardPauseDuration) {
        isPaused = true
        pausedUntil = duration.interval.map { Date().addingTimeInterval($0) }
    }

    func resumeHistory() {
        isPaused = false
        pausedUntil = nil
    }

    func shouldIgnore(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return ignoredBundleIdentifiers.contains(bundleIdentifier)
    }

    @discardableResult
    func consumeIgnoreNextCopy() -> Bool {
        guard isIgnoringNextCopy else { return false }
        isIgnoringNextCopy = false
        return true
    }

    private func poll() {
        refreshPauseState()
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard Date() >= suppressedUntil else { return }
        guard !isPaused else { return }
        let sourceBundleIdentifier = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        guard !shouldIgnore(bundleIdentifier: sourceBundleIdentifier) else { return }
        guard let snapshot = makeSnapshot(from: pasteboard) else { return }
        guard !consumeIgnoreNextCopy() else { return }
        onSnapshot?(snapshot, sourceBundleIdentifier)
    }

    private func refreshPauseState() {
        guard isPaused, let pausedUntil, Date() >= pausedUntil else { return }
        resumeHistory()
    }

    private func makeSnapshot(from pasteboard: NSPasteboard) -> ClipboardSnapshot? {
        let blockedTypes = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        ]
        if blockedTypes.contains(where: { pasteboard.types?.contains($0) == true }) { return nil }

        let text = pasteboard.string(forType: .string)
        let richTextData = pasteboard.data(forType: .rtf)
        let imageType: NSPasteboard.PasteboardType?
        let imageData: Data?
        if let data = pasteboard.data(forType: NSPasteboard.PasteboardType(UTType.gif.identifier)) {
            imageType = NSPasteboard.PasteboardType(UTType.gif.identifier)
            imageData = data
        } else if let data = pasteboard.data(forType: .png) {
            imageType = .png
            imageData = data
        } else if let data = pasteboard.data(forType: .tiff) {
            imageType = .tiff
            imageData = data
        } else if let data = pasteboard.data(forType: NSPasteboard.PasteboardType("public.jpeg")) {
            imageType = NSPasteboard.PasteboardType("public.jpeg")
            imageData = data
        } else {
            imageType = nil
            imageData = nil
        }

        let fileURLs = (pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [NSURL] ?? []).compactMap { $0 as URL }

        let snapshot = ClipboardSnapshot(
            text: text,
            richTextData: richTextData,
            imageData: imageData,
            imageType: imageType?.rawValue,
            fileURLs: fileURLs
        )
        return snapshot.isEmpty ? nil : snapshot
    }
}
